#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# Global variables
_globals() {
  _path="$( \
    export \
      _OLDPWD="$(pwd)" && \
    cd \
      "$(dirname \
           "${BASH_SOURCE[0]}")" && \
    echo \
      "$(pwd)" && \
    cd \
      "${_OLDPWD}" && \
    unset \
      _OLDPWD)"
  unset \
    _OLDPWD
  app_name="$( \
    basename \
      "${BASH_SOURCE[0]}")"
  TERMUX_PREFIX="/data/data/com.termux/files"
  _bin="/system/bin"
  _curl="${_bin}/curl"
  _unzip="${_bin}/unzip"
  _rm="${_bin}/rm"
  _mv="${_bin}/mv"
  _unzip="${_bin}/unzip"
  _arch="$( \
    uname \
      -m)"
  # TODO: Auto-fetch latest termux bootstrap
  # version until Life and DogeOS
  # continuous integration scripts
  # are ready
  _date="2025.02.02"
  _dpath="${HOME}/storage/downloads"
  _bs="bootstrap-${_arch}.zip"
  _shell="$( \
    ps \
      -hp \
      $$ | \
      awk \
        '{print $5}' || \
    ps \
      -p \
      $$ | \
      awk \
        '{print $9}' | \
	sed \
	  '/NAME/d')"
}

# Error function
# Display a message and exits
# $1: message to display when the error occurs
_msg_err() {
  local \
    _msg="${1}"
  echo \
    "${_msg}"
  exit 1
}

# Download the bootstrap
_get() {
  local \
    _curl_opts=() \
    _github="https://github.com" \
    _ns='termux-pacman' \
    _pkg='termux-packages' \
    _url \
    _repo \
    _ddirpath
  _curl_opts=(
    -L
    -O
  )
  _repo="${_github}/${_ns}/${_pkg}"
  _ddirpath="${_repo}/releases/download"
  _url="${_ddirpath}/bootstrap-${_date}-r1%2Bpacman-android-7/${_bs}"
  if [ ! -d "${HOME}/storage" ]; then
    termux-setup-storage
    # Timer to give users the time to authorize the Termux app
    # to obtain storage permission.
    sleep \
      10
    # TODO: directly get the permission if root is available
  fi
  cd \
    "${_dpath}"
  echo \
    "Downloading bootstrap" \
    "archive in '${_dpath}/${_bs}'."
  "${_curl}" \
    "${_curl_opts[@]}" \
    "${_url}"
  [[ ! "$?" -eq 0 ]] && \
    echo \
      'Check ur internet connection is' \
      'correctly working.'
  cd \
    "${OLDPWD}"
}

_integrity_check() {
  local \
    _zip="${1}" \
    _check_bad
  if [[ ! -e "${_zip}" ]]; then
    _bs_bad="true"
  elif [[ -e "${_zip}" ]]; then
    _check_bad="$( \
      "${_unzip}" \
        -t \
        "${_zip}" \
        2>&1)"
    _msg_bad_start="unzip: couldn't open"
    _msg_bad_end=": Invalid file"
    if [[ "${_check_bad}" == \
          "${_msg_bad_start}"*"${_msg_bad_end}" ]]; then
      _bs_bad="true"
    else
      _bs_bad="false"
    fi
  fi
}

# Unpacks the bootstrap, setup symlinks
_prepare() {
  local \
    _bs_bad
  echo \
    "Preparing resources" \
    "for installation."
  _bs_bad="true"
  while true; do
    _integrity_check \
      "${_dpath}/${_bs}"
    if [[ "${_bs_bad}" == "true" ]]; then
      _get
    elif [[ "${_bs_bad}" == "false" ]]; then
      echo \
        "Bootstrap archive correctly downloaded" \
        "in '${_dpath}/${_bs}'."
      break
    fi
  done
  if [[ -e "${TERMUX_PREFIX}/pacman_lock" ]]; then
    echo \
      "Run ${app_name} from a fail-safe session."
    exit
  elif [[ ! -e "${TERMUX_PREFIX}/pacman_lock" ]]; then
    mkdir \
      -p \
      "${TERMUX_PREFIX}/pacman"
    cd  \
      "${TERMUX_PREFIX}/pacman"
    "${_unzip}" \
      "${_dpath}/${_bs}"
    cat \
      SYMLINKS.txt | \
      awk \
        -F "←" \
        '{system("ln -s '"'"'"$1"'"'"' '"'"'"$2"'"'"'")}'
    touch \
      "${TERMUX_PREFIX}/pacman_lock"
  fi
  cd \
    "${OLDPWD}"
}

# Replace usr, to be run from failsafe session
_install() {
  local \
    _move_apt=() \
    _move_pacman=() \
    _move=() \
    _sh \
    _rm \
    _prepare_attempts_max \
    _prepare_attempt
  echo \
    "Bootstrapping" \
    "pre - Life / DogeOS Android" \
    "environment."
  _sh="/system/bin/sh"
  _move_apt=(
    "${_mv}"
      "${TERMUX_PREFIX}/usr"
      "${TERMUX_PREFIX}/apt"
  )
  _move_pacman=(
    "${_mv}"
      "${TERMUX_PREFIX}/pacman"
      "${TERMUX_PREFIX}/usr"
  )
  _move=(
    "${_move_apt[@]}"
    '&&'
    "${_move_pacman[@]}"
  )
  _prepare_attempts_max="300"
  _prepare_attempt="0"
  while \
    [[ ! -e "${TERMUX_PREFIX}/pacman_lock" ]] && \
    (( "${_prepare_attempt}" < "${_prepare_attempts_max}" )); do
    _prepare_attempt="$(( \
      _prepare_attempt + "1"))"
    echo \
      "Pre - Life / DogeOS environment setup ready" \
      "trigger found not found, running" \
      "prepare procedure."
    _prepare
  done
  # [[ "${_shell}" != "sh" ]] && \
  #   echo \
  #     'be sure to be running this from a fail-safe session' && \
  #   exit
  "${_sh}" \
    -c \
    "${_move[*]}"
}

_clean() {
  echo \
    "Uninstalling Debian-based" \
    "Termux environment."
  rm \
    -rf \
    "${TERMUX_PREFIX}/apt" \
    "${TERMUX_PREFIX}/pacman_lock"
}

_setup() {
  echo \
    "Setting up base" \
    "pre - Life / DogeOS software" \
    "catalogues."
  pacman-key \
    --init
  pacman-key \
    --populate
  pacman \
    -Sy
}

# auto procedure
_auto() {
  echo \
    "Auto-install selected."
  _prepare
  _install
  _clean
  _setup
}

_globals

_action="${1}"

[[ $# < 1 ]] && \
  _action='auto' && \
  echo "${_shell}"

if [[ "${_action}" == "--help" ]] || \
   [[ "${_action}" == "-h" ]]; then
  _usage_text=(
    "Usage: ${app_name} <action>\n" \
    ""
    "actions:"
    "  prepare"
    "  install"
    "  clean"
    "  setup"
  )
  printf \
    "%s\n" \
    "${_usage_text[@]}"
fi

"_${_action}"
