#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# Global variables
_globals() {
  _path="$( \
    export \
      _OLDPWD="$(pwd)" && \
    cd \
      "$(dirname \
           "${BASH_SOURCE[0]}")" && \
    echo \
      "$(pwd)" && \
    cd \
      "${_OLDPWD}" && \
    unset \
      _OLDPWD)"
  unset \
    _OLDPWD
  app_name="$( \
    basename \
      "${BASH_SOURCE[0]}")"
  TERMUX_PREFIX="/data/data/com.termux/files"
  _bin="/system/bin"
  _curl="${_bin}/curl"
  _unzip="${_bin}/unzip"
  _rm="${_bin}/rm"
  _mv="${_bin}/mv"
  _arch="arm"
  _date="2025.02.02"
  _dpath="${HOME}/storage/downloads"
  _bs="bootstrap-${_arch}.zip"
  _shell="$( \
    ps \
      -hp \
      $$ | \
      awk \
        '{print $5}' || \
    ps \
      -p \
      $$ | \
      awk \
        '{print $9}' | \
	sed \
	  '/NAME/d')"
}

# Error function
# Display a message and exits
# $1: message to display when the error occurs
_msg_err() {
  local \
    _msg="${1}"
  echo \
    "${_msg}"
  exit 1
}

# Download the bootstrap
_get() {
  local \
    _curl_opts=() \
    _github="https://github.com" \
    _ns='termux-pacman' \
    _pkg='termux-packages' \
    _url \
    _repo \
    _ddirpath
  _curl_opts=(
    -L
    -O
  )
  _repo="${_github}/${_ns}/${_pkg}"
  _ddirpath="${_repo}/releases/download"
  _url="${_ddirpath}/bootstrap-${_date}-r1%2Bpacman-android-7/${_bs}"
  [ ! -d "${HOME}/storage" ] && \
    termux-setup-storage
    sleep 10
  echo \
    "${_dpath}/${_bs}"
  [ -e "${_dpath}/${_bs}" ] && \
    return
  cd \
    "${_dpath}"
  echo \
    "downloading bootstrap"
  "${_curl}" \
    "${_curl_opts[@]}" \
    "${_url}"
  [[ "$?" -eq 0 ]] && \
    echo \
      'check if ur internet connection is working'
  cd \
    "${OLDPWD}"
}

# Unpacks the bootstrap, setup symlinks
_prepare() {
  [[ ! -e "${_dpath}/${_bs}" ]] && \
    _get
  [[ -e "${TERMUX_PREFIX}/pacman_lock" ]] && \
    echo \
      "run ${app_name} from a fail-safe session" && \
    exit
  [[ ! -e "${TERMUX_PREFIX}/pacman_lock" ]] && \
    mkdir \
      -p \
      "${TERMUX_PREFIX}/pacman" && \
    cd  \
      "${TERMUX_PREFIX}/pacman" && \
    "${_unzip}" \
      "${_dpath}/${_bs}" && \
    cat \
      SYMLINKS.txt | \
      awk \
        -F "←" \
        '{system("ln -s '"'"'"$1"'"'"' '"'"'"$2"'"'"'")}'
    touch \
      "${TERMUX_PREFIX}/pacman_lock"
  cd \
    "${OLDPWD}"
}

# Replace usr, to be run from failsafe session
_install() {
  local \
    _move_apt=() \
    _move_pacman=() \
    _move=() \
    _sh \
    _rm
  _sh="/system/bin/sh"
  _move_apt=(
    "${_mv}"
      "${TERMUX_PREFIX}/usr"
      "${TERMUX_PREFIX}/apt"
  )
  _move_pacman=(
    "${_mv}"
      "${TERMUX_PREFIX}/pacman"
      "${TERMUX_PREFIX}/usr"
  )
  _move=(
    "${_move_apt[@]}"
    '&&'
    "${_move_pacman[@]}"
  )
  [[ ! -e "${TERMUX_PREFIX}/pacman_lock" ]] && \
    echo \
      "run '${app_name}' from a normal session first" && \
    exit
  # [[ "${_shell}" != "sh" ]] && \
  #   echo \
  #     'be sure to be running this from a fail-safe session' && \
  #   exit
  "${_sh}" \
    -c \
    "${_move[*]}"
}

_clean() {
  rm \
    -rf \
    "${TERMUX_PREFIX}/apt" \
    "${TERMUX_PREFIX}/pacman_lock"
}

_setup() {
  pacman-key \
    --init
  pacman-key \
    --populate
  pacman \
    -Sy
}

# auto procedure
_auto() {
  _get
  _prepare
  _install
  _clean
  _setup
}

_globals

_action="${1}"

[[ $# < 1 ]] && \
  _action='auto' && \
  echo "${_shell}"

[[ "${_action}" == "--help" ]] && \
[[ "${_action}" == "-h" ]] && \
  echo \
    "Usage: ${app_name} <action>\n" \
    "actions: <prepare install clean>"

"_${_action}"
